"""updated audit columns constraints

Revision ID: 009ce2eefbaa
Revises: 7f24fde321f2
Create Date: 2024-11-08 11:48:24.679251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009ce2eefbaa'
down_revision = '7f24fde321f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('user_mst', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mst', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
