"""added password column

Revision ID: 00f1b37887bc
Revises: 9a9ec45c316e
Create Date: 2024-12-29 21:18:44.788872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f1b37887bc'
down_revision = '9a9ec45c316e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mst', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mst', 'password')
    # ### end Alembic commands ###
