"""added qualification column in user details

Revision ID: 6d1cc432a965
Revises: 78ec116ff489
Create Date: 2024-11-08 19:42:23.568920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1cc432a965'
down_revision = '78ec116ff489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('qualification', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'qualification')
    # ### end Alembic commands ###
