"""Added technology_mst and user_technology table

Revision ID: 78ec116ff489
Revises: 13b970a7a1c0
Create Date: 2024-11-08 13:00:03.514073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ec116ff489'
down_revision = '13b970a7a1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_mst',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_name', sa.String(length=225), nullable=False),
    sa.Column('created_tstmp', sa.DateTime(), nullable=True),
    sa.Column('updated_tstmp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_mst.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology_name')
    )
    op.create_table('user_technology',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('created_tstmp', sa.DateTime(), nullable=True),
    sa.Column('updated_tstmp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['technology_mst.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_mst.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_technology')
    op.drop_table('technology_mst')
    # ### end Alembic commands ###
