"""Initial Migration

Revision ID: 7f24fde321f2
Revises: 
Create Date: 2024-11-08 11:44:31.304270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f24fde321f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mst',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=225), nullable=False),
    sa.Column('last_name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_tstmp', sa.DateTime(), nullable=True),
    sa.Column('updated_tstmp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_mst.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('user_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('adhaar_number', sa.String(), nullable=False),
    sa.Column('college_name', sa.String(length=225), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('experience_type', sa.String(length=50), nullable=False),
    sa.Column('experience', sa.DECIMAL(), nullable=True),
    sa.Column('created_tstmp', sa.DateTime(), nullable=True),
    sa.Column('updated_tstmp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_mst.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('user_mst')
    # ### end Alembic commands ###
