"""corrected spelling mistake aadhaar number

Revision ID: 9a9ec45c316e
Revises: db74cdd936fc
Create Date: 2024-12-29 12:44:25.502283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9ec45c316e'
down_revision = 'db74cdd936fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('aadhaar_number', sa.String(), nullable=False))
    op.drop_column('user_details', 'adhaar_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('adhaar_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_details', 'aadhaar_number')
    # ### end Alembic commands ###
