"""added role_mst and user_role_map table

Revision ID: ab0161ad0877
Revises: 00f1b37887bc
Create Date: 2024-12-29 23:07:16.033560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0161ad0877'
down_revision = '00f1b37887bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_mst',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_type', sa.String(length=225), nullable=False),
    sa.Column('created_tstmp', sa.DateTime(), nullable=True),
    sa.Column('updated_tstmp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_mst.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('created_tstmp', sa.DateTime(), nullable=True),
    sa.Column('updated_tstmp', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_mst.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_mst.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_mst.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_map')
    op.drop_table('role_mst')
    # ### end Alembic commands ###
