"""updated constraints for first_name & last_name

Revision ID: de775d1b71ff
Revises: 80f13844196a
Create Date: 2024-11-08 12:19:39.389297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de775d1b71ff'
down_revision = '80f13844196a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mst', schema=None) as batch_op:
        batch_op.drop_constraint('user_mst_first_name_key', type_='unique')
        batch_op.drop_constraint('user_mst_last_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mst', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_mst_last_name_key', ['last_name'])
        batch_op.create_unique_constraint('user_mst_first_name_key', ['first_name'])

    # ### end Alembic commands ###
